## FIRST LINE/ROW: Info & Status
# First param ─┌

add_newline = false
command_timeout = 1000

[username]
format = " [$user]($style) -> "
style_user = "bold italics #fceaea"
style_root = "bold cyan"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold #494949"
trim_at = "-"
ssh_only = false
disabled = true

# Third param
[directory]
style = "yellow"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "
home_symbol = "⚚"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = false

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " 🕙 $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 └─
[character]
success_symbol = " [ξ:](cyan)"
error_symbol = "[:](red)"

[sudo]
format = "[ as $symbol]($style)"
symbol = "Divergent"
disabled = false

# SYMBOLS
[status]
symbol = "[δ](#ec5800)"
not_found_symbol = "[?](red)"
format = '[$symbol$status_common_meaning$status_signal_name$status_maybe_int]($style)'
map_symbol = true
disabled = false
not_executable_symbol = "[☥](yellow)"
sigint_symbol = "[Θ](purple)"
[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

